apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AravindHari24/gitops-second-project.git"  # Replace with your GitHub repo
    targetRevision: main
    path: "K8s"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
